name: OMS_Survival
version: '0.0.6.0'
main: com.luidenka.survival.Survival
api-version: 1.8
authors: [ Luidenka ]
commands:
  lobby:
    aliases: [l]
    description: Return to SMP Lobby
    usage: /<command>
